#!/bin/bash

set_date() {
    export TZ="America/Los_Angeles"
    A="day"
    F="full"

    if [ "$1" == "$A" ] ; then
        date +"%a"
    fi

    if [ "$1" == "$F" ] ; then
        date +"%F"
    fi

    return 0
}

set_date $@
